Repository PetCampus-Inc/daeng_v1_front, pull requests merged in 2024-10, with the labels that each got.

#244 Feat: 관리자 강아지 앨범 추가
  src/apis/admin/admin.api.ts
  src/assets/svg/pause-icon.tsx
  src/assets/svg/play-icon.tsx
  src/components/Admin/DogGallery/GridAlbum/index.tsx
  src/components/Admin/DogGallery/GridAlbum/styles.ts
  src/components/Admin/DogGallery/SinglePicture/AlbumCheckBox/index.tsx
  src/components/Admin/DogGallery/SinglePicture/AlbumCheckBox/style.ts
  src/components/Admin/DogGallery/SinglePicture/MediaViewModal/index.tsx
  src/components/Admin/DogGallery/SinglePicture/MediaViewModal/styles.ts
  src/components/Admin/DogGallery/SinglePicture/index.tsx
  src/components/Admin/DogGallery/SinglePicture/styles.ts
  src/components/common/VideoPlayer/index.tsx
  src/components/common/VideoPlayer/style.ts
  src/components/common/index.ts
  src/hooks/api/admin/dogs.ts
  src/hooks/common/useSaveMedia.tsx
  src/hooks/native/useNativeAction.ts
  src/pages/AdminDogDetailInfoPage/DogDetailInfoPage.tsx
  src/pages/DogDetailGalleryPage/DogGalleryPage.tsx
  src/types/admin/admin.types.ts
  src/types/native/action.types.ts
  src/utils/is/nativeAction.ts
  src/utils/thumb.ts
Labels: feat, refactor

#243 Fix: (QA) 가입신청 승인 이후 프로필 설정 페이지
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/Member/Profile/Edit/NickNameEdit.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/styles.ts
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
Labels: fix, refactor

#245 Fix: (QA) 견주 마이페이지
  src/apis/member/enrollment.api.ts
  src/apis/member/member.api.ts
  src/components/Enrollment/Stepper/MemberSubmitButton.tsx
  src/components/Member/MyPage/Cards/AddMyDogCard.tsx
  src/components/Member/MyPage/Cards/MyDogCard.tsx
  src/components/Member/MyPage/Cards/RejectedCard.tsx
  src/components/Member/MyPage/Cards/WaitingCard.tsx
  src/components/Member/MyPage/MyDogInfo/Box/DoglistBox.tsx
  src/components/Member/MyPage/hooks/useDogRejected.ts
  src/components/Member/MyPage/hooks/useEnrollmentStorage.ts
  src/components/Member/Profile/Button/SaveDogProfileButton.tsx
  src/components/common/NavBar/NavBar.tsx
  src/constants/queryKey.ts
  src/hooks/api/admin/enroll.ts
  src/hooks/api/member/enroll.ts
  src/hooks/api/member/member.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MemberPage/MemberAddDogProfileEditPage.tsx
  src/pages/MemberPage/MemberEnrollmentFunnel.tsx
  src/store/member.ts
  src/types/member/main.types.ts
Labels: fix, feat, refactor, QA

#246 Fix: (QA) Textarea AutoResizing 적용 안되는 버그 해결
  src/components/Admin/AttendCare/AttendCareGallery/CommentBox.tsx
  src/components/Admin/AttendCareNotice/WriteNotice/index.tsx
  src/components/Admin/DogDetailInfo/DogInfo/DogMemo.tsx
  src/components/Admin/EnrollmentForm/CreateForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/CreateForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/CreateForm/PolicyInfo.tsx
  src/components/Admin/EnrollmentForm/CreateForm/TicketInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/PolicyInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/TicketInfo.tsx
  src/components/Admin/EnrollmentForm/MemberReadForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/MemberReadForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/MemberReadForm/PolicyInfo.tsx
  src/components/Admin/EnrollmentForm/MemberReadForm/TicketInfo.tsx
  src/components/Admin/EnrollmentForm/ReadForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/ReadForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/ReadForm/PolicyInfo.tsx
  src/components/Admin/EnrollmentForm/ReadForm/TicketInfo.tsx
  src/components/Enrollment/Form/DogInfo.tsx
  src/components/Enrollment/Form/PickDropInfo.tsx
  src/components/Enrollment/Form/PolicyInfo.tsx
  src/components/Enrollment/Form/TicketInfo.tsx
  src/components/Enrollment/MemberDogInfoForm/DogInfo.tsx
  src/components/Enrollment/MemberDogReadForm/DogInfo.tsx
  src/components/Enrollment/MemberDogReadForm/PickDropInfo.tsx
  src/components/Enrollment/MemberDogReadForm/PolicyInfo.tsx
  src/components/Enrollment/MemberDogReadForm/TicketInfo.tsx
  src/components/common/BottomSheet/InfoBottomSheet/styles.ts
  src/components/common/TextArea/index.tsx
  src/components/common/TextArea/styles.ts
  src/components/common/Textarea/index.tsx
  src/components/common/Textarea/styles.ts
  src/components/common/index.ts
  src/pages/TestPage.tsx
  src/routes/AppRouter.tsx
  src/types/native/message.types.ts
Labels: QA

#247 Fix/Ui: (QA) 온보딩 프로필 설정 페이지
  src/components/Member/Profile/BottomSheet/RoleBottomSheet.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/styles.ts
Labels: refactor, ui, QA

#248 Fix/Ui: 프로필 등록 페이지 호칭 선택 bottomSheet Ui 수정
  src/components/Member/Profile/BottomSheet/RoleBottomSheet.tsx
Labels: fix, ui

#249 Feat: 강아지 변경 시트 강아지 추가 기능 연결
  src/apis/member/enrollment.api.ts
  src/assets/images/placeholder-dog.png
  src/components/Home/DogManagerPopup/index.tsx
  src/components/Home/DogManagerPopup/styles.ts
  src/constants/path.ts
  src/constants/queryKey.ts
  src/hooks/api/member/enroll.ts
  src/hooks/api/member/member.ts
  src/pages/EnrollmentPage/MemberSchoolReEnrollmentPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/TestPage.tsx
  src/types/member/main.types.ts
  src/types/native/message.types.ts
Labels: QA

#250 Hotfix: 가입신청서 플로우 중 유치원 검색 다음 버튼 클릭 시 팝업 드는 이슈 해결
  src/pages/SignUpPage/SearchSchoolPage.tsx
Labels: hotfix

#252 Refactor/Fix: 배변 상태 컴포넌트 리팩토링 및 하드코딩 이미지 제거
  src/assets/svg/poop-hard.tsx
  src/assets/svg/poop-healthy.tsx
  src/assets/svg/poop-not-brown.tsx
  src/assets/svg/poop-warning.tsx
  src/assets/svg/poop-watery.tsx
  src/components/Admin/AttendCare/card/AddDogCard.tsx
  src/components/Admin/AttendCare/card/MainDogCard.tsx
  src/components/Admin/AttendCare/card/SelectDogCard.tsx
  src/components/Admin/AttendCare/list/AddDogAvatar.tsx
  src/components/Admin/AttendCare/list/AddDogList.tsx
  src/components/Admin/AttendCare/list/SelectDogList.tsx
  src/components/Admin/AttendCare/modal/PreviousInfoGuideBottomSheet.tsx
  src/components/Admin/AttendCareNotice/DogInfoBox/index.tsx
  src/components/Admin/AttendCareNotice/PastAgendaBottomSheet/index.tsx
  src/components/Admin/AttendCareNotice/WriteNotice/index.tsx
  src/components/Admin/Attendance/Card/AttendDogCard.tsx
  src/components/Admin/Attendance/Card/DogCard.tsx
  src/components/Admin/Attendance/Dialog/CallMemberBottomSheet.tsx
  src/components/Admin/Attendance/List/AttendanceAvatar.tsx
  src/components/Admin/Attendance/List/AttendanceSearchList.tsx
  src/components/Admin/Attendance/styles.ts
  src/components/Admin/DogDetailInfo/AttendanceRecord/DailyAgenda/DailyAgenda.tsx
  src/components/Admin/DogDetailInfo/DogInfo/AboutOwnerCard.tsx
  src/components/Admin/SchoolInfo/Modal/CallSchoolBottomSheet.tsx
  src/components/Agenda/DailyAgenda/DailyAgenda.tsx
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
  src/components/common/BottomSheet/CallBottomSheet/CallSchoolBottomSheet.tsx
  src/components/common/Dropdown/styles.ts
  src/components/common/Field/index.tsx
  src/components/common/PoopBox/index.tsx
  src/components/common/PoopBox/styles.ts
  src/components/common/PoopStatusGroup/index.tsx
  src/components/common/PoopStatusGroup/styles.ts
  src/components/common/Select/DayMultiCheck/index.tsx
  src/components/common/index.ts
  src/hooks/api/admin/care.ts
  src/pages/AdminAttendCarePage/AttendCareNoticePage/AttendCareNoticePage.tsx
  src/pages/AdminAttendancePage/AttendancePage.tsx
  src/pages/MemberPage/MemberMyPage.tsx
  src/types/admin/attendance.type.ts
  src/types/admin/care.types.ts
  src/utils/is/index.ts
Labels: fix, refactor

#253 Refactor: Calendar 컴포넌트 추상화 진행
  src/apis/admin/attendance.api.ts
  src/apis/member/dogs.ts
  src/assets/svg/arrow-left-icon.tsx
  src/assets/svg/arrow-right-icon.tsx
  src/assets/svg/types.ts
  src/components/Admin/AttendCare/AttendCareMain/AddDogButton.tsx
  src/components/Admin/AttendCare/button/MainSendCard.tsx
  src/components/Admin/DogDetailInfo/AttendanceRecord/Calendar/Calendar.tsx
  src/components/Admin/DogDetailInfo/AttendanceRecord/Calendar/MonthlyCalendar.tsx
  src/components/Admin/DogDetailInfo/AttendanceRecord/Calendar/styles.ts
  src/components/Admin/DogDetailInfo/AttendanceRecord/DailyAgenda/DailyAgenda.tsx
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/Admin/MyPage/PrincipalProfile/index.tsx
  src/components/Admin/MyPage/TeacherProfile/index.tsx
  src/components/Admin/SchoolManage/MemberWaitingCard/index.tsx
  src/components/Admin/SchoolManage/SimpleMembershipApplication/index.tsx
  src/components/Agenda/Calendar/Calendar.tsx
  src/components/Agenda/Calendar/MonthPicker.tsx
  src/components/Agenda/Calendar/MonthlyCalendar.tsx
  src/components/Agenda/Calendar/WeeklyCalendar.tsx
  src/components/Agenda/Calendar/styles.ts
  src/components/Home/Dashboard/DogCard.tsx
  src/components/Home/Dashboard/DogNote.tsx
  src/components/Member/DogInfo/AttendanceTicketInfo/index.tsx
  src/components/Member/MyPage/Buttons/GotoSchoolInfoButton.tsx
  src/components/Member/MyPage/Cards/WaitingCard.tsx
  src/components/common/Button/Templates/MoreButton.tsx
  src/components/common/Calendar/AllCalendar.tsx
  src/components/common/Calendar/MonthCalendar.tsx
  src/components/common/Calendar/index.ts
  src/components/common/Calendar/month-picker.tsx
  src/components/common/Calendar/monthly-calendar.tsx
  src/components/common/Calendar/styles.ts
  src/components/common/Calendar/types.ts
  src/components/common/Calendar/useAdjustButton.ts
  src/components/common/Calendar/useCalendar.ts
  src/components/common/Calendar/useWeekSwipe.ts
  src/components/common/Calendar/weekly-calendar.tsx
  src/components/common/LightBox/Arrows.tsx
  src/hooks/api/admin/dogs.ts
  src/hooks/api/member/dogs.ts
  src/pages/AdminMyPage/AdminSettingPage.tsx
  src/pages/AgendaPage/AgendaPage.tsx
  src/styles/system/style-modules.ts
  src/types/admin/attendance.type.ts
  src/types/member/dogs.ts
  src/utils/date.ts
Labels: refactor

#255 Fix: [2차 QA] 이슈 픽스
  src/components/Admin/AttendCare/card/MainDogCard.tsx
  src/components/Admin/Attendance/Card/AttendDogCard.tsx
  src/components/Admin/Attendance/Card/DogCard.tsx
  src/components/Admin/Attendance/List/AttendanceAvatar.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormListPage.tsx
  src/pages/EnrollmentPage/NewEnrollmentPage.tsx
  src/routes/PrivateRouter.tsx
Labels: fix

#259 Fix: 2차 QA 픽스
  src/apis/admin/admin.api.ts
  src/apis/admin/mypage.api.ts
  src/components/Admin/DogDetailInfo/DogInfo/DogMemo.tsx
  src/components/Admin/DogDetailInfo/DogInfo/styles.ts
  src/components/Admin/DogDetailInfo/Notice/Notice.tsx
  src/components/Admin/MyPage/EditProfile/index.tsx
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/Admin/MyPage/PrincipalProfile/index.tsx
  src/components/Admin/MyPage/TeacherProfile/index.tsx
  src/components/Admin/SchoolInfo/SchoolInfoCard.tsx
  src/components/Enrollment/Form/TicketInfo.tsx
  src/components/SignIn/button/SubmitButton.tsx
  src/components/SignUp/SignUpForm/SchoolInfo.tsx
  src/components/common/NavBar/NavBar.tsx
  src/components/common/NavBar/styles.ts
  src/pages/AdminMyPage/PrincipalMyPage.tsx
  src/pages/AdminMyPage/SchoolInfoEditPage.tsx
  src/pages/AdminMyPage/TeacherMyPage.tsx
  src/pages/EnrollmentPage/MemberDogCreateEnrollmentPage.tsx
  src/pages/EnrollmentPage/MemberSchoolReEnrollmentPage.tsx
  src/pages/EnrollmentPage/NewEnrollmentPage.tsx
  src/pages/SignUpPage/EnrollSchoolPage.tsx
  src/styles/GlobalStyle.ts
  src/types/admin/admin.types.ts
  src/types/admin/mypage.types.ts
Labels: fix

#261 Fix: [2차 QA] 프로필 등록 관련 이슈
  src/apis/member/member.api.ts
  src/components/Member/MyPage/MemberProfile/index.tsx
  src/components/Member/MyPage/MyMemberinfo/index.tsx
  src/components/Member/Profile/Box/ProfileActiveBox.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/styles.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MemberPage/MemberMyPage.tsx
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
Labels: fix, QA_2

#265 Fix: [2차 QA] 강아지 상세 페이지 이슈
  src/apis/member/enrollment.api.ts
  src/components/Member/DogInfo/DogDetailInfoEdit/Buttons/SaveButton.tsx
  src/components/Member/DogInfo/Enrollment/EnrollmentDogDetail.tsx
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
  src/components/Member/DogInfo/styles.ts
  src/constants/path.ts
  src/hooks/api/member/member.ts
  src/pages/MemberPage/MemberDogInfoEditPage.tsx
  src/pages/MemberPage/MemberEnrollmentDogInfoPage.tsx
  src/types/member/main.types.ts
Labels: fix, QA_2

#266 Feat: 어드민 사진첩 스크롤/상세 보기 페이지 구현
  src/assets/svg/pause-icon.tsx
  src/assets/svg/play-icon.tsx
  src/components/Admin/DogGallery/GalleryViewer/MediaDetailPopup/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/MediaDetailPopup/styles.ts
  src/components/Admin/DogGallery/GalleryViewer/ThumbnailVideo/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/ThumbnailVideo/styles.ts
  src/components/Admin/DogGallery/GalleryViewer/VideoPlayer/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/VideoPlayer/style.ts
  src/components/Admin/DogGallery/GalleryViewer/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/styles.ts
  src/components/Admin/DogGallery/GalleryViewer/types.ts
  src/components/Admin/DogGallery/GridAlbum/index.tsx
  src/components/Admin/DogGallery/SinglePicture/index.tsx
  src/constants/path.ts
  src/pages/DogGalleryViewerPage/DogGalleryViewerPage.tsx
  src/pages/index.ts
  src/routes/AdminRoutes.tsx
Labels: feat, QA_2

#263 Feat: 상세주소 필드 필수값 처리
  src/components/Admin/EnrollmentForm/CreateForm/MemberInfo.tsx
  src/components/Admin/EnrollmentForm/styles.ts
  src/components/Enrollment/MemberDogInfoForm/DogInfo.tsx
  src/components/Enrollment/NewForm/DogInfo.tsx
  src/components/Enrollment/NewForm/MemberInfo.tsx
  src/components/Enrollment/NewForm/PickDropInfo.tsx
  src/components/Enrollment/NewForm/PolicyInfo.tsx
  src/components/Enrollment/NewForm/TicketInfo.tsx
  src/components/Enrollment/NewForm/index.ts
  src/components/Enrollment/NewForm/styles.ts
  src/components/Enrollment/Stepper/SubmitButton.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/styles.ts
  src/components/Member/MyPage/MyMemberInfoEdit/MyInfoEdit.tsx
  src/components/SignUp/SignUpForm/SchoolInfo.tsx
  src/components/common/Postcode/index.tsx
  src/components/common/Postcode/styles.ts
  src/pages/AdminMyPage/SchoolInfoEditPage.tsx
  src/pages/EnrollmentPage/MemberDogCreateEnrollmentPage.tsx
  src/pages/EnrollmentPage/MemberSchoolReEnrollmentPage.tsx
  src/pages/EnrollmentPage/NewEnrollmentPage.tsx
Labels: feat, QA_2

#267 Fix: layout 컴포넌트 스타일 수정
  src/components/common/Layout/index.tsx
  src/components/common/Layout/styles.ts
  src/pages/ApprovalStatusPage/ApprovalStatusPage.tsx
  src/pages/LoginPage/AdminLoginPage.tsx
  src/pages/LoginPage/LoginPage.tsx
Labels: fix

#269 Fix: 관리자 강아지 상세페이지 추가, 파일 다운로드 네이티브 연결
  src/components/Admin/AttendCare/AttendCareGallery/SendFileButton.tsx
  src/components/Admin/AttendCareNotice/FlexPhotosWithTime/index.tsx
  src/components/Admin/AttendCareNotice/FlexPhotosWithTime/styles.ts
  src/components/Admin/AttendCareNotice/PhotoAlbum/index.tsx
  src/components/Admin/AttendCareNotice/PhotoAlbum/styles.ts
  src/components/Admin/Attendance/Dialog/CallMemberBottomSheet.tsx
  src/components/Admin/DogDetailInfo/DogInfo/AboutDogCard.tsx
  src/components/Admin/DogDetailInfo/DogInfo/AboutOwnerCard.tsx
  src/components/Admin/DogDetailInfo/DogInfo/styles.ts
  src/components/Admin/DogGallery/GalleryViewer/ThumbnailVideo/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/ThumbnailVideo/styles.ts
  src/components/Admin/DogGallery/GridAlbum/index.tsx
  src/components/Admin/DogGallery/SinglePicture/AlbumCheckBox/style.ts
  src/components/Admin/DogGallery/SinglePicture/MediaViewModal/index.tsx
  src/components/Admin/DogGallery/SinglePicture/MediaViewModal/styles.ts
  src/components/Admin/DogGallery/SinglePicture/index.tsx
  src/components/Admin/DogGallery/SinglePicture/styles.ts
  src/components/Admin/MyPage/Button/index.tsx
  src/components/Admin/SchoolInfo/Modal/CallSchoolBottomSheet.tsx
  src/components/Agenda/DailyAgenda/DailyAgenda.tsx
  src/components/Album/Button/SaveButton.tsx
  src/components/Album/GridView/ImageGridItem.tsx
  src/components/Album/GridView/SaveButton.tsx
  src/components/Album/GridView/styles.ts
  src/components/Album/LightBox/CommentCarouselLightBox.tsx
  src/components/Album/LightBox/SaveOptionDropdown.tsx
  src/components/Album/PhotoView.tsx
  src/components/Album/Slide/AlbumSlide.tsx
  src/components/Home/ImageAlbum/ImageSlider.tsx
  src/components/Home/ImageComment/ImageComment.tsx
  src/components/Home/ImageComment/ImageCommentSlider.tsx
  src/components/Home/ImageComment/SaveButton.tsx
  src/components/Home/ImageComment/styles.ts
  src/components/Member/DogInfo/SchoolInfo/index.tsx
  src/components/common/BottomSheet/CallBottomSheet/CallSchoolBottomSheet.tsx
  src/components/common/BottomSheet/CallBottomSheet/index.tsx
  src/components/common/Field/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/PoopStatusGroup/index.tsx
  src/components/common/PoopStatusGroup/styles.ts
  src/constants/path.ts
  src/hooks/api/member/school.ts
  src/hooks/common/useSaveMedia.tsx
  src/pages/AdminAttendCarePage/AttendCareSelectDogPage.tsx
  src/pages/AdminDogDetailInfoPage/DogInfoFormPage.tsx
  src/pages/AdminMyPage/PrincipalMyPage.tsx
  src/pages/AdminMyPage/TeacherMyPage.tsx
  src/pages/DogDetailGalleryPage/DogGalleryPage.tsx
  src/pages/DogGalleryViewerPage/DogGalleryViewerPage.tsx
  src/pages/SignUpPage/SearchSchoolPage.tsx
  src/pages/index.ts
  src/routes/AdminRoutes.tsx
  src/utils/date.ts
Labels: fix

#271 Refactor: 리뷰 내용 적용 및 Slider 로직 수정
  src/assets/svg/pause-icon.tsx
  src/assets/svg/play-icon.tsx
  src/components/Admin/DogGallery/GalleryViewer/VideoPlayer/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/VideoPlayer/style.ts
  src/components/Admin/DogGallery/GalleryViewer/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/styles.ts
  src/routes/AdminRoutes.tsx
Labels: refactor, QA_2

#274 Fix: 상세 페이지 강아지 프로필 이미지 표시 로직 수정
  src/assets/svg/arrow-left-icon.tsx
  src/assets/svg/arrow-right-icon.tsx
  src/components/Admin/AttendCare/AttendCareGallery/SendFileButton.tsx
  src/components/Admin/AttendCare/AttendCareGallery/SubmitButton.tsx
  src/components/Admin/AttendCareNotice/DailyAgenda/CreateAgenda.tsx
  src/components/Admin/AttendCareNotice/PhotoAlbum/ImageGrid.tsx
  src/components/Admin/AttendCareNotice/PhotoAlbum/PhotoAlbum.tsx
  src/components/Admin/AttendCareNotice/PhotoAlbum/styles.ts
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/Admin/MyPage/PrincipalProfile/index.tsx
  src/components/Admin/MyPage/TeacherProfile/index.tsx
  src/components/Album/LightBox/CommentCarouselLightBox.tsx
  src/components/Album/LightBox/SaveModeLightBox.tsx
  src/components/Home/Dashboard/DogCard.tsx
  src/components/Home/Dashboard/DogNote.tsx
  src/components/Member/DogInfo/Main/CarouselModal/index.tsx
  src/components/common/Button/Templates/MoreButton.tsx
  src/components/common/Calendar/MonthCalendar.tsx
  src/components/common/Calendar/month-picker.tsx
  src/components/common/Calendar/weekly-calendar.tsx
  src/components/common/Dropdown/DropdownTrigger.tsx
  src/components/common/LightBox/Arrows.tsx
  src/constants/queryKey.ts
  src/hooks/api/admin/care.ts
  src/hooks/api/admin/dogs.ts
  src/pages/AdminAttendCarePage/AttendCareNoticePage/AgendaView.tsx
  src/pages/AdminAttendCarePage/AttendCareNoticePage/AttendCareNoticePage.tsx
  src/pages/AdminAttendCarePage/AttendCareNoticePage/PhotoAlbumView.tsx
  src/pages/AdminDogDetailInfoPage/AttendanceRecord.tsx
  src/pages/AdminDogDetailInfoPage/DogDetailInfoPage.tsx
  src/pages/AdminMyPage/AdminSettingPage.tsx
  src/pages/MemberPage/MemberSettingPage.tsx
Labels: fix, QA_2

#275 fix/ui: 어드민 사진 상세 보기 이미지 비율 수정
  src/components/Admin/DogGallery/GalleryViewer/MediaDetailPopup/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/VideoPlayer/style.ts
  src/components/Admin/DogGallery/GalleryViewer/index.tsx
  src/components/Admin/DogGallery/GalleryViewer/styles.ts
Labels: fix, QA_2

#276 Fix: 강아지 유치원 상세페이지 이슈 수정
  src/apis/member/enrollment.api.ts
  src/components/Member/MyPage/Cards/MyDogCard.tsx
  src/components/Member/SchoolInfo/PreviousSchoolInfo.tsx
  src/components/Member/SchoolInfo/index.tsx
  src/components/Member/SchoolInfo/styles.ts
  src/constants/memberDogStatus.ts
  src/hooks/api/member/school.ts
  src/pages/MemberPage/MemberSchoolInfoPage.tsx
  src/types/member/school.types.ts
Labels: fix, QA_2
