Repository PetCampus-Inc/daeng_v1_front, pull requests merged in 2024-08, with the labels that each got.

#193 Feat: 강아지 상세 정보 (정보 수정 - 프로필 사진 추가)
  src/apis/member/member.api.ts
  src/components/Member/DogInfo/DogDetailInfoEdit/Buttons/SaveButton.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/DogDetailInfoEdit.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/ProfileUpdateBox.tsx
  src/components/Member/DogInfo/index.tsx
  src/components/Member/DogInfo/styles.ts
  src/components/Member/MyPage/Buttons/RoleEditeButton.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyInfoEdit.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyProfileEdit.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/styles.ts
  src/components/Member/Profile/AddDogProfile.tsx
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/Member/Profile/Edit/NickNameEdit.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/Onboarding/NickName.tsx
  src/components/Member/Profile/Onboarding/Profile.tsx
  src/components/Member/Profile/OnboardingProfile.tsx
  src/components/Member/Profile/styles.ts
  src/components/common/Header/index.tsx
  src/constants/profile.ts
  src/hooks/common/useUploadProfile.ts
  src/pages/MemberPage/MemberDogInfoEditPage.tsx
  src/pages/MemberPage/MemberMyInfoEditPage.tsx
  src/pages/MemberPage/MemberMyInfoPage.tsx
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
  src/pages/index.ts
  src/routes/MemberRoutes.tsx
  src/types/member/main.types.ts
Labels: feat, refactor, ui

#197 Feat: `홈` 등원기록 Monthly Calendar 구현
  src/assets/svg/arrow-left-icon.tsx
  src/assets/svg/arrow-right-icon.tsx
  src/assets/svg/x-icon.jsx
  src/components/Admin/AttendCare/AttendCareMain/AddDogButton.tsx
  src/components/Admin/SchoolManage/MemberWaitingCard/index.tsx
  src/components/Admin/SchoolManage/SimpleMembershipApplication/index.tsx
  src/components/Agenda/Calendar/Calendar.tsx
  src/components/Agenda/Calendar/MonthlyCalendar.tsx
  src/components/Agenda/Calendar/WeeklyCalendar.tsx
  src/components/Agenda/Calendar/styles.ts
  src/components/Agenda/index.ts
  src/components/Member/DogInfo/index.tsx
  src/components/Member/MyPage/Cards/MyDogCard.tsx
  src/components/Member/MyPage/Cards/WaitingCard.tsx
  src/components/common/FloatingOverlay/FloatingOverlay.tsx
  src/pages/HomePage/Agenda/index.tsx
  src/styles/foundations/shadows.ts
Labels: feat

#202 Feat: `홈` 등원기록 Weekly Calendar 및 Swipe 기능 구현
  src/assets/svg/arrow-down-icon.tsx
  src/components/Admin/DogDetailInfo/DogInfo/Calendar/index.tsx
  src/components/Admin/DogDetailInfo/DogInfo/styles.ts
  src/components/Agenda/Calendar/Calendar.tsx
  src/components/Agenda/Calendar/MonthPicker.tsx
  src/components/Agenda/Calendar/MonthlyCalendar.tsx
  src/components/Agenda/Calendar/WeeklyCalendar.tsx
  src/components/Agenda/Calendar/styles.ts
  src/components/Agenda/Calendar/useWeekSwipe.ts
  src/components/common/Box/styles.ts
  src/components/common/Text/index.tsx
  src/components/common/Text/styles.ts
  src/styles/CalendarStyle.ts
  src/styles/GlobalStyle.ts
Labels: feat

#203 feat: 캘린더에서 유효 범위가 아닌경우 날짜 이동 비활성화 처리
  src/apis/member/dogs.ts
  src/assets/svg/arrow-left-icon.tsx
  src/assets/svg/arrow-right-icon.tsx
  src/assets/svg/poop-hard.tsx
  src/assets/svg/poop-healthy.tsx
  src/assets/svg/poop-not-brown.tsx
  src/assets/svg/poop-warning.tsx
  src/assets/svg/poop-watery.tsx
  src/components/Admin/AttendCareNotice/FlexPhotosWithTime/index.tsx
  src/components/Admin/Attendance/AttendanceCard/DogCard.tsx
  src/components/Admin/DogDetailInfo/Ticket/PastTicket/index.tsx
  src/components/Agenda/Calendar/Calendar.tsx
  src/components/Agenda/Calendar/MonthPicker.tsx
  src/components/Agenda/Calendar/MonthlyCalendar.tsx
  src/components/Agenda/Calendar/WeeklyCalendar.tsx
  src/components/Agenda/Calendar/styles.ts
  src/components/Agenda/Calendar/useWeekSwipe.ts
  src/components/Agenda/DailyAgenda/AgendaData.tsx
  src/components/Agenda/DailyAgenda/DailyAgenda.tsx
  src/components/Agenda/DailyAgenda/styles.ts
  src/components/Enrollment/MemberDogReadForm/DogInfo.tsx
  src/components/common/PoopBox/index.tsx
  src/constants/path.ts
  src/constants/queryKey.ts
  src/hooks/api/member/dogs.ts
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormSubmitPage.tsx
  src/pages/AgendaPage/AgendaPage.tsx
  src/pages/HomePage/Agenda/index.tsx
  src/pages/HomePage/Album/index.tsx
  src/pages/MemberPage/MemberDogInfoEditPage.tsx
  src/pages/index.ts
  src/routes/MemberRoutes.tsx
  src/types/member/dogs.ts
  src/utils/date.ts
Labels: feat

#160 Feat: 강아지 상세 정보 (예방 접종 파일 업로드)
  src/apis/member/member.api.ts
  src/components/Member/DogInfo/DogDetailInfoEdit/Buttons/SaveButton.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/DogDetailInfoEdit.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/ProfileUpdateBox.tsx
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
  src/components/Member/DogInfo/Main/Box/DogMemoBox.tsx
  src/components/Member/DogInfo/Main/Box/VaccinationBox.tsx
  src/components/Member/DogInfo/Main/CarouselModal/index.tsx
  src/components/Member/DogInfo/Main/CarouselModal/styles.ts
  src/components/Member/DogInfo/Main/DogInfo/InfoText.tsx
  src/components/Member/DogInfo/Main/hooks/useUploadVaccintion.ts
  src/components/Member/DogInfo/index.tsx
  src/components/Member/DogInfo/styles.ts
  src/components/Member/MyPage/Buttons/RoleEditeButton.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyInfoEdit.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyProfileEdit.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/styles.ts
  src/components/Member/Profile/AddDogProfile.tsx
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/Member/Profile/Edit/NickNameEdit.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/Onboarding/NickName.tsx
  src/components/Member/Profile/Onboarding/Profile.tsx
  src/components/Member/Profile/OnboardingProfile.tsx
  src/components/Member/Profile/styles.ts
  src/components/common/BottomSheet/InfoBottomSheet/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Modal/CarouselModal/index.tsx
  src/components/common/Modal/index.ts
  src/constants/profile.ts
  src/constants/s3File.ts
  src/hooks/api/member/member.ts
  src/hooks/common/useUploadProfile.ts
  src/pages/MemberPage/MemberDogInfoEditPage.tsx
  src/pages/MemberPage/MemberMyInfoEditPage.tsx
  src/pages/MemberPage/MemberMyInfoPage.tsx
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
  src/pages/index.ts
  src/routes/MemberRoutes.tsx
  src/types/member/main.types.ts
Labels: feat

#206 Refactor: 어드민 마이페이지 UI 마크업
  src/apis/admin/mypage.api.ts
  src/assets/svg/add-brown-icon.tsx
  src/assets/svg/alert-brown-icon.tsx
  src/assets/svg/calendar-expire.tsx
  src/assets/svg/calendar.tsx
  src/assets/svg/care-dog-icon.tsx
  src/assets/svg/check-circle-brown.tsx
  src/assets/svg/ellipse-orange-icon.tsx
  src/assets/svg/list-yellow-circle-icon.tsx
  src/assets/svg/map-pin-icon.tsx
  src/assets/svg/phone-basic.tsx
  src/assets/svg/photo-icon.tsx
  src/assets/svg/send-alarm.tsx
  src/components/Admin/MyPage/AlertSetting/index.tsx
  src/components/Admin/MyPage/AlertSetting/styles.ts
  src/components/Admin/MyPage/Button/index.tsx
  src/components/Admin/MyPage/DeleteAccount/index.tsx
  src/components/Admin/MyPage/EditProfile/index.tsx
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/Admin/MyPage/PrincipalProfile/index.tsx
  src/components/Admin/MyPage/TeacherProfile/index.tsx
  src/components/Admin/Notification/NotificationList.tsx
  src/components/Admin/SchoolInfo/SchoolInfoCard.tsx
  src/components/Admin/SchoolInfo/index.tsx
  src/components/Admin/SchoolInfo/styles.ts
  src/components/common/Header/index.tsx
  src/constants/adminNotification.tsx
  src/constants/path.ts
  src/hooks/api/admin/mypage.ts
  src/hooks/api/useGetPrincipalInfo.ts
  src/pages/AdminMyPage/AdminSettingPage.tsx
  src/pages/AdminMyPage/PrincipalMyPage.tsx
  src/pages/AdminMyPage/SchoolInfoEditPage.tsx
  src/pages/AdminMyPage/SchoolInfoPage.tsx
  src/pages/AdminMyPage/TeacherMyPage.tsx
  src/pages/AdminNotificationPage/AdminNotificationPage.tsx
  src/pages/index.ts
  src/routes/AdminRoutes.tsx
  src/types/admin/admin.types.ts
  src/types/admin/mypage.types.ts
Labels: refactor, ui

#205 feat: Tabs 공통 컴포넌트 추가
  .storybook/preview.tsx
  src/components/common/Tabs/index.ts
  src/components/common/Tabs/styles.ts
  src/components/common/Tabs/tabs-ui.stories.tsx
  src/components/common/Tabs/tabs-ui.tsx
  src/components/common/Tabs/tabs.stories.tsx
  src/components/common/Tabs/tabs.tsx
Labels: feat, common

#207 Refactor: Role, Status 타입 및 Approval 페이지 리팩토링
  src/components/Admin/MyPage/AlertSetting/index.tsx
  src/components/Admin/MyPage/DeleteAccount/index.tsx
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/SignUp/ApprovalStatus/ApprovalFailed.tsx
  src/components/SignUp/ApprovalStatus/ApprovalPending.tsx
  src/components/SignUp/ApprovalStatus/ApprovalSuccess.tsx
  src/components/SignUp/ApprovalStatus/RegisterSuccess.tsx
  src/components/SignUp/ApprovalStatus/index.ts
  src/components/SignUp/RoleBox/index.tsx
  src/components/common/NavBar/AdminNavBar.tsx
  src/components/common/index.ts
  src/constants/path.ts
  src/hooks/api/signin.ts
  src/hooks/api/signup.ts
  src/pages/AdminMyPage/PrincipalMyPage.tsx
  src/pages/AdminMyPage/TeacherMyPage.tsx
  src/pages/ApprovalStatusPage/ApprovalStatusPage.tsx
  src/pages/MemberPage/MemberSchoolSearchPage.tsx
  src/pages/SignUpPage/AccountSettingPage.tsx
  src/pages/SignUpPage/AdminSignUpFunnel.tsx
  src/pages/SignUpPage/ApprovalStatusPage.tsx
  src/pages/SignUpPage/EnrollSchoolPage.tsx
  src/pages/SignUpPage/RoleSelectPage.tsx
  src/pages/SignUpPage/SearchSchoolPage.tsx
  src/pages/SignUpPage/SignUpFunnel.tsx
  src/pages/index.ts
  src/routes/AdminAuthRouter.tsx
  src/routes/AppRouter.tsx
  src/types/admin/admin.types.ts
  src/types/admin/attendance.type.ts
  src/types/common/approval.types.ts
  src/types/common/role.types.ts
  src/types/common/status.types.ts
  src/types/member/auth.types.ts
  src/types/member/main.types.ts
  src/utils/is.ts
Labels: refactor

#208 Feat/Refactor: 견주 마이페이지 (견주 프로필 사진 수정)
  src/components/Member/DogInfo/DogDetailInfoEdit/ProfileUpdateBox.tsx
  src/components/Member/MyPage/Buttons/RoleEditButton.tsx
  src/components/Member/MyPage/Buttons/SaveButton.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyInfoEdit.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyProfileEdit.tsx
  src/components/Member/MyPage/MyMemberinfo/index.tsx
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
  src/components/Member/Profile/styles.ts
  src/constants/queryKey.ts
  src/hooks/api/member/member.ts
  src/pages/MemberPage/MemberMyInfoEditPage.tsx
  src/types/member/main.types.ts
Labels: feat, refactor

#212 Refactor: Svg Icon interface 개선
  src/assets/svg/alert-filled-icon.tsx
  src/assets/svg/arrow-down-icon.tsx
  src/assets/svg/arrow-left-icon.tsx
  src/assets/svg/arrow-right-icon.tsx
  src/assets/svg/attendance-black-icon.tsx
  src/assets/svg/attendance-icon.tsx
  src/assets/svg/boy-icon.jsx
  src/assets/svg/boy-icon.tsx
  src/assets/svg/calendar-expire.tsx
  src/assets/svg/calendar.tsx
  src/assets/svg/care-dog-icon.tsx
  src/assets/svg/dog-card-icon.tsx
  src/assets/svg/dog-circle-icon.tsx
  src/assets/svg/dog-filled-icon.tsx
  src/assets/svg/dog-glasses-circle-icon.tsx
  src/assets/svg/foot-icon.tsx
  src/assets/svg/foot-round-icon.tsx
  src/assets/svg/girl-icon.jsx
  src/assets/svg/girl-icon.tsx
  src/assets/svg/pencil-filled-icon.tsx
  src/assets/svg/pencil-icon.tsx
  src/assets/svg/phone-icon.tsx
  src/assets/svg/principal-icon.jsx
  src/assets/svg/principal-selected-icon.jsx
  src/assets/svg/remain-count-icon.tsx
  src/assets/svg/teacher-icon.jsx
  src/assets/svg/teacher-selected-icon.jsx
  src/assets/svg/types.ts
  src/assets/svg/x-circle-filled-icon.tsx
  src/components/Admin/AttendCare/empty/EmptyDog.tsx
  src/components/SignUp/RoleBox/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Tabs/styles.ts
  src/components/common/Tabs/tabs.tsx
  src/constants/adminNotification.tsx
Labels: refactor

#213 Refactor: DogInfoPage의 데이터 로딩 개선을 위한 Prefetch 적용
  src/components/Admin/DogDetailInfo/AttendanceRecord/index.tsx
  src/components/Admin/DogDetailInfo/DogInfo/Calendar/index.tsx
  src/components/Admin/DogDetailInfo/DogInfo/index.tsx
  src/components/Admin/DogDetailInfo/Notice/index.tsx
  src/components/Admin/DogDetailInfo/Ticket/index.tsx
  src/components/common/Calendar/AllCalendar.tsx
  src/hooks/api/admin/attendance.ts
  src/hooks/api/admin/dogs.ts
  src/hooks/api/useGetPrecautions.ts
  src/pages/AdminDogDetailPage/DogInfoPage.tsx
  src/types/admin/attendance.type.ts
Labels: refactor
