Repository PetCampus-Inc/daeng_v1_front, pull requests merged in 2024-09, with the labels that each got.

#219 Fix: 가입신청서 생성 시 pickDropInfo requireItemList에서 제외
  src/components/Admin/EnrollmentForm/CreateForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/PickDropInfo.tsx
  src/components/Admin/EnrollmentForm/Stepper/Navigation.tsx
  src/components/Admin/EnrollmentForm/Stepper/NavigationButton.tsx
  src/components/Admin/EnrollmentForm/Stepper/SubmitButton.tsx
  src/components/Admin/EnrollmentForm/TicketType/index.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormEditPage.tsx
Labels: fix

#218 Refactor: Native 통신 로직 개선
  src/apis/member/member.api.ts
  src/constants/path.ts
  src/hooks/native/useNative.tsx
  src/hooks/native/useNativeEvent.ts
  src/hooks/native/useNativeMessage.ts
  src/libs/nativeReceiver.ts
  src/pages/RedirectPage/NativeRedirectPage.tsx
  src/pages/index.ts
  src/routes/AppRouter.tsx
  src/types/member/auth.types.ts
  src/types/native/event.types.ts
  src/types/native/message.types.ts
  src/utils/is.ts
  src/utils/is/index.ts
  src/utils/is/nativeEvent.ts
  src/utils/is/nativeMessage.ts
Labels: refactor

#221 Fix/Ui: 가공되어 반환되는 데이터로 인한 UI 수정 (강아지 상세정보 페이지)
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
Labels: fix, ui

#223 Fix: 가입신청서 UI 수정
  src/components/Enrollment/Form/PickDropInfo.tsx
  src/components/Enrollment/styles.ts
  src/constants/step.ts
  src/pages/EnrollmentPage/NewEnrollmentPage.tsx
Labels: fix

#225 Refactor: Router Path 구조 변경
  src/components/Admin/AttendCare/AttendCareGallery/SendFileButton.tsx
  src/components/Admin/AttendCare/AttendCareGallery/SubmitButton.tsx
  src/components/Admin/AttendCare/AttendCareMain.tsx
  src/components/Admin/AttendCare/AttendCareMain/CareOptionDropdown.tsx
  src/components/Admin/AttendCare/card/MainDogCard.tsx
  src/components/Admin/AttendCare/empty/EmptyDog.tsx
  src/components/Admin/AttendCareNotice/PhotoAlbum/index.tsx
  src/components/Admin/DogDetailInfo/NewTicketForm/SubmitButton.tsx
  src/components/Admin/DogDetailInfo/Ticket/NewTicketBottomSheet.tsx
  src/components/Admin/MyPage/DeleteAccount/index.tsx
  src/components/Admin/MyPage/MyPageCard/InfoCard.tsx
  src/components/Admin/SchoolManage/MemberWaitingCard/index.tsx
  src/components/Admin/SchoolManage/MenuCard/index.tsx
  src/components/Admin/SchoolManage/SimpleMembershipApplication/index.tsx
  src/components/Album/AlbumHeader.tsx
  src/components/Enrollment/Stepper/MemberSubmitButton.tsx
  src/components/Home/Dashboard/DogNote.tsx
  src/components/Home/HomeImageAlbum.tsx
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
  src/components/Member/MyPage/Cards/AddMyDogCard.tsx
  src/components/Member/MyPage/Cards/MyDogCard.tsx
  src/components/Member/MyPage/MemberProfile/index.tsx
  src/components/Setting/index.tsx
  src/components/SignIn/button/LinkButton.tsx
  src/components/SignUp/ApprovalStatus/ApprovalFailed.tsx
  src/components/SignUp/ApprovalStatus/ApprovalPending.tsx
  src/components/SignUp/ApprovalStatus/ApprovalSuccess.tsx
  src/components/SignUp/ApprovalStatus/RegisterSuccess.tsx
  src/components/common/Header/index.tsx
  src/components/common/NavBar/AdminNavBar.tsx
  src/constants/adminNotification.tsx
  src/constants/funnelPath.ts
  src/constants/navBar.tsx
  src/constants/path.ts
  src/hooks/api/admin/care.ts
  src/hooks/api/admin/enroll.ts
  src/hooks/api/admin/mypage.ts
  src/hooks/api/member/member.ts
  src/hooks/common/useLogout.ts
  src/hooks/common/useRoleBasedPath.ts
  src/libs/AuthAxios/index.ts
  src/pages/AdminDogDetailInfoPage/DogDetailInfoPage.tsx
  src/pages/AdminMyPage/AdminDeleteCompletePage.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormCreateFunnel.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormDetailPage.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormEditFunnel.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/SchoolManageEnrollmentPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MemberPage/MemberEnrollmentFunnel.tsx
  src/pages/MemberPage/MemberMyInfoPage.tsx
  src/pages/SignUpPage/AdminSignUpFunnel.tsx
  src/pages/SignUpPage/SignUpFunnel.tsx
  src/routes/AdminRoutes.tsx
  src/routes/AppRouter.tsx
  src/routes/MemberRoutes.tsx
Labels: refactor

#227 Fix: 어댑터에서 남아있는 adminId, memberId 제거
  src/components/Admin/AttendCare/AttendCareGallery/upload/Thumbnail.tsx
  src/components/Admin/AttendCare/AttendCareGallery/upload/styles.ts
  src/components/Admin/MyPage/EditProfile/index.tsx
  src/components/Admin/SchoolManage/MenuCard/index.tsx
  src/components/Enrollment/Stepper/MemberSubmitButton.tsx
  src/components/Enrollment/Stepper/SubmitButton.tsx
  src/components/Home/DogManagerPopup/index.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/common/NavBar/NavBar.tsx
  src/constants/path.ts
  src/hooks/common/useUploadProfile.ts
  src/index.tsx
  src/libs/adapters/FormToServerAdapter.ts
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormEditPage.tsx
  src/pages/EnrollmentPage/MemberDogCreateEnrollmentPage.tsx
  src/pages/EnrollmentPage/MemberSchoolReEnrollmentPage.tsx
  src/pages/EnrollmentPage/NewEnrollmentPage.tsx
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
  src/types/admin/admin.types.ts
  src/types/admin/attendance.type.ts
  src/types/admin/enrollment.types.ts
  src/types/member/enrollment.types.ts
  src/types/member/main.types.ts
Labels: fix

#228 Feat/Fix: 승인 이후 프로필 등록 페이지로 연결
  src/components/Member/DogInfo/DogDetailInfoEdit/DogDetailInfoEdit.tsx
  src/components/Member/MyPage/Buttons/SaveButton.tsx
  src/components/Member/MyPage/MyMemberInfoEdit/MyProfileEdit.tsx
  src/components/Member/Profile/AddDogProfile.tsx
  src/components/Member/Profile/Box/ProfileActiveBox.tsx
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Button/SaveProfileButton.tsx
  src/components/Member/Profile/Edit/NickNameEdit.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/Member/Profile/Onboarding/Profile.tsx
  src/components/Member/Profile/styles.ts
  src/hooks/common/useUploadProfile.ts
  src/pages/MemberProfileEditPage/MemberProfileEditPage.tsx
Labels: fix, feat

#230 Feat: 가입신청서 예방접종 파일 업로드 기능 구현
  src/assets/svg/x-circle-icon.tsx
  src/components/Admin/AttendCare/AttendCareGallery/upload/Thumbnail.tsx
  src/components/Admin/AttendCare/AttendCareGallery/upload/styles.ts
  src/components/Admin/EnrollmentForm/CreateForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/EditForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/MemberReadForm/DogInfo.tsx
  src/components/Admin/EnrollmentForm/ReadForm/DogInfo.tsx
  src/components/Enrollment/Form/DogInfo.tsx
  src/components/Enrollment/ImageUpload/ImageUploadInput.tsx
  src/components/Enrollment/ImageUpload/LightBox.tsx
  src/components/Enrollment/ImageUpload/styles.ts
  src/components/Enrollment/MemberDogInfoForm/DogInfo.tsx
  src/components/Enrollment/MemberDogReadForm/DogInfo.tsx
  src/components/Enrollment/Stepper/SubmitButton.tsx
  src/components/common/ImageUpload/ImageModal/index.tsx
  src/components/common/ImageUpload/ImageModal/styles.ts
  src/components/common/ImageUpload/index.tsx
  src/components/common/LightBox/styles.ts
  src/hooks/common/useS3/types.ts
  src/hooks/common/useS3/use-s3-upload.ts
  src/styles/StyleModule.ts
Labels: feat

#234 Hotfix: profile 에러 수정
  src/apis/admin/mypage.api.ts
  src/components/Member/Profile/Box/ProfileUploadBox.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/ProfileEdit.tsx
Labels: hotfix

#235 Feat/Fix: UI 추가 / 온보딩 픽스
  src/apis/admin/admin.api.ts
  src/apis/member/member.api.ts
  src/assets/images/new_enrollform.jpg
  src/components/Admin/Attendance/AttendanceMain.tsx
  src/components/Admin/Attendance/Button/SortSelectBox.tsx
  src/components/Admin/Attendance/Dialog/SortOptionsBottomSheet.tsx
  src/components/Admin/EnrollmentForm/CreateForm/PickDropInfo.tsx
  src/components/Admin/SchoolManage/MACarousel/index.tsx
  src/components/Admin/SchoolManage/MenuCard/index.tsx
  src/components/Admin/SchoolManage/NewEnrollmentFormBottomSheet/index.tsx
  src/components/Admin/SchoolManage/NewEnrollmentFormBottomSheet/styles.ts
  src/components/Enrollment/Form/DogInfo.tsx
  src/components/Enrollment/Stepper/SubmitButton.tsx
  src/components/SignUp/ApprovalStatus/ApprovalFailed.tsx
  src/components/SignUp/ApprovalStatus/ApprovalPending.tsx
  src/components/SignUp/SearchSchool/SchoolListDropdown.tsx
  src/components/SignUp/SearchSchool/SchoolSearchInputBox.tsx
  src/constants/path.ts
  src/constants/storage.ts
  src/hooks/api/admin/enroll.ts
  src/hooks/api/member/member.ts
  src/hooks/api/signup.ts
  src/hooks/api/useGetNewEnrollment.ts
  src/hooks/common/useRoleBasedPath.ts
  src/hooks/common/useTicketFieldArray.ts
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormCreatePage.tsx
  src/pages/AdminSchoolMangePage/EnrollmentPage/EnrollmentFormListPage.tsx
  src/pages/ApprovalStatusPage/ApprovalStatusPage.tsx
  src/pages/MemberPage/MemberEnrollmentFunnel.tsx
  src/pages/SignUpPage/AdminSignUpFunnel.tsx
  src/pages/SignUpPage/EnrollSchoolPage.tsx
  src/pages/SignUpPage/SearchSchoolPage.tsx
  src/pages/SignUpPage/SignUpFunnel.tsx
  src/pages/SignUpPage/TeacherReJoinPage.tsx
  src/pages/index.ts
  src/routes/AdminRoutes.tsx
  src/routes/AppRouter.tsx
  src/routes/MemberRoutes.tsx
  src/store/admin.ts
  src/store/form.ts
  src/store/member.ts
Labels: fix, feat, refactor

#217 Feat/Refactor: 견주 마이페이지 (강아지 카드 클릭, 최초 강아지 프로필 등록 페이지)
  public/images/empty-image1.svg
  src/apis/member/member.api.ts
  src/assets/images/error-dog.svg
  src/assets/svg/my-page-dog.jsx
  src/components/Home/DisconnectionNotice/DisconnectionNotice.tsx
  src/components/Home/DisconnectionNotice/styles.ts
  src/components/Member/MyPage/Buttons/styles.ts
  src/components/Member/MyPage/Cards/MyDogCard.tsx
  src/components/Member/MyPage/Cards/RejectedCard.tsx
  src/components/Member/MyPage/Cards/styles.ts
  src/components/Member/MyPage/MyDogInfo/Box/DoglistBox.tsx
  src/components/Member/MyPage/MyDogInfo/Box/TitleBox.tsx
  src/components/Member/MyPage/MyDogInfo/index.tsx
  src/components/Member/MyPage/hooks/useDogRejected.ts
  src/components/Member/MyPage/hooks/useEnrollmentStorage.ts
  src/components/Member/Profile/Button/SaveDogProfileButton.tsx
  src/components/Member/Profile/Edit/ProfileCreate.tsx
  src/components/Member/Profile/Edit/RoleEdit.tsx
  src/components/common/NavBar/NavBar.tsx
  src/constants/memberDogStatus.ts
  src/hooks/api/member/member.ts
  src/hooks/common/useLocalStorage.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MemberPage/MemberAddDogProfileEditPage.tsx
  src/routes/MemberRoutes.tsx
  src/store/member.ts
  src/types/member/main.types.ts
Labels: feat, refactor

#242 Fix: [QA] 관리자 프로필 이슈 픽스
  src/apis/admin/admin.api.ts
  src/apis/admin/mypage.api.ts
  src/components/Admin/MyPage/EditProfile/ProfileUploadBox/index.tsx
  src/components/Admin/MyPage/EditProfile/ProfileUploadBox/style.ts
  src/components/Admin/MyPage/EditProfile/index.tsx
  src/components/Admin/MyPage/EditProfile/styles.ts
  src/components/Admin/MyPage/PrincipalProfile/index.tsx
  src/components/Admin/MyPage/PrincipalProfile/styles.ts
  src/components/Admin/MyPage/TeacherProfile/index.tsx
  src/components/Admin/MyPage/TeacherProfile/styles.ts
  src/hooks/api/admin/mypage.ts
  src/hooks/api/signin.ts
  src/hooks/common/useAdminInfo.ts
  src/hooks/common/useS3/use-s3-upload.ts
  src/pages/AdminMyPage/PrincipalMyPage.tsx
  src/pages/AdminMyPage/SchoolInfoEditPage.tsx
  src/pages/AdminMyPage/TeacherMyPage.tsx
  src/store/admin.ts
  src/types/admin/admin.types.ts
Labels: fix

#241 Fix: (QA) 견주홈 - 강아지 상세정보
  src/apis/member/enrollment.api.ts
  src/components/Enrollment/MemberDogReadForm/DogInfo.tsx
  src/components/Enrollment/MemberDogReadForm/MemberInfo.tsx
  src/components/Enrollment/MemberDogReadForm/PickDropInfo.tsx
  src/components/Enrollment/MemberDogReadForm/PolicyInfo.tsx
  src/components/Enrollment/MemberDogReadForm/TicketInfo.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/Buttons/SaveButton.tsx
  src/components/Member/DogInfo/DogDetailInfoEdit/DogDetailInfoEdit.tsx
  src/components/Member/DogInfo/Main/Box/DogInfoBox.tsx
  src/components/Member/DogInfo/index.tsx
  src/constants/s3File.ts
  src/pages/MemberPage/MemberDogInfoEditPage.tsx
  src/types/member/main.types.ts
Labels: fix
